# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Tests

on:
  push:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel mypy pylint
        pip install -r requirements.txt
    - name: PyLint
      run: |
        pylint --disable=R,C,W pydeezer
    - name: Install
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/py_deezer-*.whl  --force-reinstall
    - name: Check if we can run the command
      run: |
        pydeezer --help
        
